<?php

declare(strict_types=1);

namespace Sabri\CF03\Persistence;

final class Schema
{
    public const VERSION = '2.0.0';

    /** @return array<string,string> */
    public static function tables(string $prefix): array
    {
        $charset = 'DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';
        return [
            'products' => "CREATE TABLE {$prefix}sabri_cf03_products (id bigint unsigned NOT NULL AUTO_INCREMENT, product_id varchar(128) NOT NULL, kind varchar(32) NOT NULL, billing_type varchar(32) NOT NULL, owner varchar(128) NOT NULL, entitlement_mapping varchar(191) NULL, lifecycle_state varchar(32) NOT NULL, policy_version varchar(64) NOT NULL, approval_ref varchar(191) NULL, staged_by varchar(191) NULL, approved_by varchar(191) NULL, effective_at datetime(6) NULL, record_version bigint unsigned NOT NULL DEFAULT 1, created_at datetime(6) NOT NULL, updated_at datetime(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY product_id(product_id), KEY lifecycle_state(lifecycle_state)) {$charset};",
            'prices' => "CREATE TABLE {$prefix}sabri_cf03_price_versions (id bigint unsigned NOT NULL AUTO_INCREMENT, price_version_id varchar(128) NOT NULL, product_id varchar(128) NOT NULL, amount_minor bigint unsigned NOT NULL, currency char(3) NOT NULL, region varchar(32) NOT NULL, tax_mode varchar(32) NOT NULL, lifecycle_state varchar(32) NOT NULL, effective_from datetime(6) NOT NULL, effective_until datetime(6) NULL, refund_policy_version varchar(64) NOT NULL, cancellation_policy_version varchar(64) NOT NULL, approval_ref varchar(191) NULL, snapshot_hash char(64) NOT NULL, record_version bigint unsigned NOT NULL DEFAULT 1, created_at datetime(6) NOT NULL, updated_at datetime(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY price_version_id(price_version_id), KEY product_region_currency(product_id,region,currency,effective_from), KEY price_state(lifecycle_state)) {$charset};",
            'customer_refs' => "CREATE TABLE {$prefix}sabri_cf03_payment_customer_refs (id bigint unsigned NOT NULL AUTO_INCREMENT, actor_ref varchar(191) NOT NULL, provider varchar(64) NOT NULL, provider_customer_ref varchar(191) NOT NULL, fingerprint_hash char(64) NULL, data_region varchar(32) NULL, state varchar(32) NOT NULL, record_version bigint unsigned NOT NULL DEFAULT 1, created_at datetime(6) NOT NULL, updated_at datetime(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY actor_provider(actor_ref,provider), UNIQUE KEY provider_customer(provider,provider_customer_ref)) {$charset};",
            'intents' => "CREATE TABLE {$prefix}sabri_cf03_payment_intents (id bigint unsigned NOT NULL AUTO_INCREMENT, intent_id varchar(128) NOT NULL, actor_ref varchar(191) NOT NULL, product_id varchar(128) NOT NULL, price_version_id varchar(128) NULL, amount_minor bigint unsigned NOT NULL, currency char(3) NOT NULL, provider varchar(64) NOT NULL, provider_ref varchar(191) NULL, state varchar(32) NOT NULL, failure_code varchar(64) NULL, idempotency_key varchar(191) NOT NULL, request_hash char(64) NOT NULL, expires_at datetime(6) NOT NULL, record_version bigint unsigned NOT NULL DEFAULT 1, trace_id varchar(128) NOT NULL, created_at datetime(6) NOT NULL, updated_at datetime(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY intent_id(intent_id), UNIQUE KEY idempotency_scope(idempotency_key,actor_ref), KEY actor_created(actor_ref,created_at), KEY provider_ref(provider,provider_ref), KEY intent_state(state,updated_at)) {$charset};",
            'provider_events' => "CREATE TABLE {$prefix}sabri_cf03_provider_events (id bigint unsigned NOT NULL AUTO_INCREMENT, provider varchar(64) NOT NULL, provider_event_id varchar(191) NOT NULL, event_type varchar(96) NOT NULL, raw_body_hash char(64) NOT NULL, signature_key_version varchar(64) NOT NULL, signature_timestamp datetime(6) NOT NULL, received_at datetime(6) NOT NULL, mapped_state varchar(32) NOT NULL, status varchar(32) NOT NULL, intent_id varchar(128) NULL, trace_id varchar(128) NOT NULL, processed_at datetime(6) NULL, PRIMARY KEY(id), UNIQUE KEY provider_event(provider,provider_event_id), KEY event_status(status,received_at), KEY event_intent(intent_id)) {$charset};",
            'ledger_transactions' => "CREATE TABLE {$prefix}sabri_cf03_ledger_transactions (id bigint unsigned NOT NULL AUTO_INCREMENT, transaction_id varchar(128) NOT NULL, source_type varchar(64) NOT NULL, source_ref varchar(191) NOT NULL, effective_at datetime(6) NOT NULL, recorded_at datetime(6) NOT NULL, actor_ref varchar(191) NOT NULL, reason varchar(255) NOT NULL, period_id varchar(32) NOT NULL, reversal_of varchar(128) NULL, trace_id varchar(128) NOT NULL, PRIMARY KEY(id), UNIQUE KEY transaction_id(transaction_id), UNIQUE KEY source_once(source_type,source_ref), KEY period_effective(period_id,effective_at), KEY reversal_of(reversal_of)) {$charset};",
            'ledger_entries' => "CREATE TABLE {$prefix}sabri_cf03_ledger_entries (id bigint unsigned NOT NULL AUTO_INCREMENT, transaction_id varchar(128) NOT NULL, account varchar(128) NOT NULL, direction varchar(8) NOT NULL, amount_minor bigint unsigned NOT NULL, currency char(3) NOT NULL, source_ref varchar(191) NOT NULL, PRIMARY KEY(id), KEY transaction_id(transaction_id), KEY account_currency(account,currency), KEY source_ref(source_ref)) {$charset};",
            'recurring_consents' => "CREATE TABLE {$prefix}sabri_cf03_recurring_consents (id bigint unsigned NOT NULL AUTO_INCREMENT, consent_id varchar(128) NOT NULL, actor_ref varchar(191) NOT NULL, product_id varchar(128) NOT NULL, amount_minor bigint unsigned NOT NULL, currency char(3) NOT NULL, interval_code varchar(32) NOT NULL, next_charge_at datetime(6) NOT NULL, terms_hash char(64) NOT NULL, cancellation_path varchar(255) NOT NULL, state varchar(32) NOT NULL, captured_at datetime(6) NOT NULL, revoked_at datetime(6) NULL, PRIMARY KEY(id), UNIQUE KEY consent_id(consent_id), KEY actor_product(actor_ref,product_id)) {$charset};",
            'subscriptions' => "CREATE TABLE {$prefix}sabri_cf03_subscriptions (id bigint unsigned NOT NULL AUTO_INCREMENT, subscription_id varchar(128) NOT NULL, actor_ref varchar(191) NOT NULL, product_id varchar(128) NOT NULL, price_version_id varchar(128) NOT NULL, consent_id varchar(128) NULL, provider_ref varchar(191) NULL, state varchar(32) NOT NULL, current_period_end datetime(6) NULL, grace_until datetime(6) NULL, paused_until datetime(6) NULL, cancellation_effective_at datetime(6) NULL, policy_version varchar(64) NOT NULL, record_version bigint unsigned NOT NULL DEFAULT 1, created_at datetime(6) NOT NULL, updated_at datetime(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY subscription_id(subscription_id), KEY actor_state(actor_ref,state), KEY provider_ref(provider_ref)) {$charset};",
            'usage_authorizations' => "CREATE TABLE {$prefix}sabri_cf03_usage_authorizations (id bigint unsigned NOT NULL AUTO_INCREMENT, authorization_id varchar(128) NOT NULL, actor_ref varchar(191) NOT NULL, meter_unit varchar(64) NOT NULL, unit_rate_minor bigint unsigned NOT NULL, authorized_units bigint unsigned NOT NULL, hard_cap_minor bigint unsigned NOT NULL, currency char(3) NOT NULL, terms_hash char(64) NOT NULL, valid_until datetime(6) NOT NULL, created_at datetime(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY authorization_id(authorization_id), KEY actor_validity(actor_ref,valid_until)) {$charset};",
            'usage_facts' => "CREATE TABLE {$prefix}sabri_cf03_usage_facts (id bigint unsigned NOT NULL AUTO_INCREMENT, usage_id varchar(128) NOT NULL, authorization_id varchar(128) NOT NULL, units bigint unsigned NOT NULL, amount_minor bigint unsigned NOT NULL, currency char(3) NOT NULL, producer_ref varchar(128) NOT NULL, signature_hash char(64) NOT NULL, occurred_at datetime(6) NOT NULL, received_at datetime(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY usage_id(usage_id), KEY authorization_id(authorization_id)) {$charset};",
            'invoices' => "CREATE TABLE {$prefix}sabri_cf03_invoices (id bigint unsigned NOT NULL AUTO_INCREMENT, invoice_id varchar(128) NOT NULL, invoice_number varchar(128) NOT NULL, actor_ref varchar(191) NOT NULL, status varchar(32) NOT NULL, amount_minor bigint unsigned NOT NULL, currency char(3) NOT NULL, snapshot_hash char(64) NOT NULL, snapshot_json longtext NOT NULL, issued_at datetime(6) NOT NULL, voided_at datetime(6) NULL, PRIMARY KEY(id), UNIQUE KEY invoice_id(invoice_id), UNIQUE KEY invoice_number(invoice_number), KEY actor_issued(actor_ref,issued_at)) {$charset};",
            'refunds' => "CREATE TABLE {$prefix}sabri_cf03_refunds (id bigint unsigned NOT NULL AUTO_INCREMENT, refund_id varchar(128) NOT NULL, intent_id varchar(128) NOT NULL, amount_minor bigint unsigned NOT NULL, currency char(3) NOT NULL, refundable_balance_minor bigint unsigned NULL, requester_ref varchar(191) NOT NULL, reviewer_ref varchar(191) NULL, executor_ref varchar(191) NULL, reason varchar(255) NOT NULL, decision_reason varchar(255) NULL, policy_version varchar(64) NOT NULL, state varchar(32) NOT NULL, provider_ref varchar(191) NULL, record_version bigint unsigned NOT NULL DEFAULT 1, requested_at datetime(6) NOT NULL, updated_at datetime(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY refund_id(refund_id), KEY intent_state(intent_id,state), KEY provider_ref(provider_ref)) {$charset};",
            'chargebacks' => "CREATE TABLE {$prefix}sabri_cf03_chargebacks (id bigint unsigned NOT NULL AUTO_INCREMENT, case_id varchar(128) NOT NULL, provider varchar(64) NOT NULL, provider_case_ref varchar(191) NOT NULL, intent_id varchar(128) NOT NULL, amount_minor bigint unsigned NOT NULL, currency char(3) NOT NULL, reason_code varchar(64) NOT NULL, response_deadline datetime(6) NOT NULL, evidence_hash char(64) NULL, provider_fee_minor bigint unsigned NULL, state varchar(32) NOT NULL, record_version bigint unsigned NOT NULL DEFAULT 1, created_at datetime(6) NOT NULL, updated_at datetime(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY case_id(case_id), UNIQUE KEY provider_case(provider,provider_case_ref), KEY deadline_state(response_deadline,state)) {$charset};",
            'donations' => "CREATE TABLE {$prefix}sabri_cf03_donations (id bigint unsigned NOT NULL AUTO_INCREMENT, donation_id varchar(128) NOT NULL, donor_ref varchar(191) NOT NULL, amount_minor bigint unsigned NOT NULL, currency char(3) NOT NULL, purpose_code varchar(128) NOT NULL, recurring tinyint(1) NOT NULL DEFAULT 0, recurring_consent_id varchar(128) NULL, provider_ref varchar(191) NULL, receipt_ref varchar(191) NULL, state varchar(32) NOT NULL, anonymous_public tinyint(1) NOT NULL DEFAULT 1, record_version bigint unsigned NOT NULL DEFAULT 1, created_at datetime(6) NOT NULL, updated_at datetime(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY donation_id(donation_id), KEY donor_created(donor_ref,created_at), KEY provider_ref(provider_ref)) {$charset};",
            'settlements' => "CREATE TABLE {$prefix}sabri_cf03_settlement_batches (id bigint unsigned NOT NULL AUTO_INCREMENT, batch_id varchar(128) NOT NULL, provider varchar(64) NOT NULL, gross_minor bigint unsigned NOT NULL, fee_minor bigint unsigned NOT NULL, refund_minor bigint unsigned NOT NULL, net_minor bigint unsigned NOT NULL, currency char(3) NOT NULL, source_hash char(64) NOT NULL, settled_at datetime(6) NOT NULL, imported_at datetime(6) NOT NULL, status varchar(32) NOT NULL, PRIMARY KEY(id), UNIQUE KEY provider_batch(provider,batch_id), KEY settled_at(settled_at)) {$charset};",
            'settlement_lines' => "CREATE TABLE {$prefix}sabri_cf03_settlement_lines (id bigint unsigned NOT NULL AUTO_INCREMENT, batch_id varchar(128) NOT NULL, line_ref varchar(191) NOT NULL, line_type varchar(32) NOT NULL, amount_minor bigint unsigned NOT NULL, currency char(3) NOT NULL, PRIMARY KEY(id), UNIQUE KEY batch_line(batch_id,line_ref), KEY line_ref(line_ref)) {$charset};",
            'reconciliation_exceptions' => "CREATE TABLE {$prefix}sabri_cf03_reconciliation_exceptions (id bigint unsigned NOT NULL AUTO_INCREMENT, exception_id varchar(128) NOT NULL, batch_id varchar(128) NOT NULL, exception_type varchar(64) NOT NULL, source_ref varchar(191) NOT NULL, expected_minor bigint unsigned NOT NULL, actual_minor bigint unsigned NOT NULL, currency char(3) NOT NULL, material tinyint(1) NOT NULL DEFAULT 1, state varchar(32) NOT NULL, owner_ref varchar(191) NULL, accepted_risk_ref varchar(191) NULL, created_at datetime(6) NOT NULL, resolved_at datetime(6) NULL, PRIMARY KEY(id), UNIQUE KEY exception_id(exception_id), KEY batch_state(batch_id,state)) {$charset};",
            'finance_periods' => "CREATE TABLE {$prefix}sabri_cf03_finance_periods (id bigint unsigned NOT NULL AUTO_INCREMENT, period_id varchar(32) NOT NULL, state varchar(32) NOT NULL, reviewed_by varchar(191) NULL, approved_by varchar(191) NULL, accepted_risk_ref varchar(191) NULL, closed_at datetime(6) NULL, record_version bigint unsigned NOT NULL DEFAULT 1, PRIMARY KEY(id), UNIQUE KEY period_id(period_id), KEY period_state(state)) {$charset};",
            'adjustments' => "CREATE TABLE {$prefix}sabri_cf03_adjustments (id bigint unsigned NOT NULL AUTO_INCREMENT, adjustment_id varchar(128) NOT NULL, source_transaction_id varchar(128) NOT NULL, amount_minor bigint unsigned NOT NULL, currency char(3) NOT NULL, reason_code varchar(64) NOT NULL, evidence_hash char(64) NOT NULL, requester_ref varchar(191) NOT NULL, approver_ref varchar(191) NULL, executor_ref varchar(191) NULL, state varchar(32) NOT NULL, record_version bigint unsigned NOT NULL DEFAULT 1, requested_at datetime(6) NOT NULL, executed_at datetime(6) NULL, PRIMARY KEY(id), UNIQUE KEY adjustment_id(adjustment_id), KEY source_transaction(source_transaction_id)) {$charset};",
            'fraud_reviews' => "CREATE TABLE {$prefix}sabri_cf03_fraud_reviews (id bigint unsigned NOT NULL AUTO_INCREMENT, review_id varchar(128) NOT NULL, subject_ref varchar(191) NOT NULL, risk_score int unsigned NOT NULL, signals_json longtext NOT NULL, hold_until datetime(6) NOT NULL, state varchar(32) NOT NULL, reviewer_ref varchar(191) NULL, decision_reason varchar(255) NULL, record_version bigint unsigned NOT NULL DEFAULT 1, created_at datetime(6) NOT NULL, updated_at datetime(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY review_id(review_id), KEY hold_state(hold_until,state)) {$charset};",
            'exports' => "CREATE TABLE {$prefix}sabri_cf03_export_jobs (id bigint unsigned NOT NULL AUTO_INCREMENT, job_id varchar(128) NOT NULL, requester_ref varchar(191) NOT NULL, specification_hash char(64) NOT NULL, maximum_rows int unsigned NOT NULL, state varchar(32) NOT NULL, encrypted_object_ref varchar(255) NULL, manifest_hash char(64) NULL, expires_at datetime(6) NOT NULL, record_version bigint unsigned NOT NULL DEFAULT 1, created_at datetime(6) NOT NULL, updated_at datetime(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY job_id(job_id), KEY requester_state(requester_ref,state), KEY expiry(expires_at)) {$charset};",
            'idempotency' => "CREATE TABLE {$prefix}sabri_cf03_idempotency (id bigint unsigned NOT NULL AUTO_INCREMENT, scope varchar(96) NOT NULL, idempotency_key varchar(191) NOT NULL, actor_ref varchar(191) NOT NULL, request_hash char(64) NOT NULL, state varchar(32) NOT NULL, result_ref varchar(191) NULL, created_at datetime(6) NOT NULL, completed_at datetime(6) NULL, expires_at datetime(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY scope_key(scope,idempotency_key), KEY actor_created(actor_ref,created_at), KEY expiry(expires_at)) {$charset};",
            'outbox' => "CREATE TABLE {$prefix}sabri_cf03_outbox (id bigint unsigned NOT NULL AUTO_INCREMENT, event_id varchar(128) NOT NULL, event_type varchar(96) NOT NULL, aggregate_id varchar(128) NOT NULL, aggregate_version varchar(64) NOT NULL, schema_version varchar(32) NOT NULL, trace_id varchar(128) NOT NULL, payload_json longtext NOT NULL, payload_hash char(64) NOT NULL, state varchar(32) NOT NULL, attempts int unsigned NOT NULL DEFAULT 0, available_at datetime(6) NOT NULL, leased_until datetime(6) NULL, last_error_code varchar(64) NULL, created_at datetime(6) NOT NULL, delivered_at datetime(6) NULL, PRIMARY KEY(id), UNIQUE KEY event_id(event_id), KEY delivery(state,available_at), KEY aggregate(aggregate_id,aggregate_version)) {$charset};",
            'audit' => "CREATE TABLE {$prefix}sabri_cf03_audit_events (id bigint unsigned NOT NULL AUTO_INCREMENT, audit_id varchar(128) NOT NULL, actor_ref varchar(191) NOT NULL, purpose varchar(128) NOT NULL, action varchar(128) NOT NULL, outcome varchar(32) NOT NULL, trace_id varchar(128) NOT NULL, metadata_json longtext NOT NULL, metadata_hash char(64) NOT NULL, previous_hash char(64) NOT NULL, entry_hash char(64) NOT NULL, created_at datetime(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY audit_id(audit_id), UNIQUE KEY entry_hash(entry_hash), KEY trace_id(trace_id), KEY actor_created(actor_ref,created_at)) {$charset};",
            'retention_ledger' => "CREATE TABLE {$prefix}sabri_cf03_retention_ledger (id bigint unsigned NOT NULL AUTO_INCREMENT, record_type varchar(64) NOT NULL, record_ref varchar(191) NOT NULL, data_class varchar(8) NOT NULL, created_at datetime(6) NOT NULL, expires_at datetime(6) NULL, delete_mode varchar(32) NOT NULL, legal_hold tinyint(1) NOT NULL DEFAULT 0, legal_hold_ref varchar(191) NULL, actioned_at datetime(6) NULL, PRIMARY KEY(id), UNIQUE KEY record_once(record_type,record_ref), KEY expiry_hold(expires_at,legal_hold)) {$charset};",
            'provider_registry' => "CREATE TABLE {$prefix}sabri_cf03_provider_registry (id bigint unsigned NOT NULL AUTO_INCREMENT, provider_id varchar(64) NOT NULL, mode varchar(32) NOT NULL, currencies_json longtext NOT NULL, data_region varchar(32) NULL, configuration_hash char(64) NOT NULL, key_version varchar(64) NULL, state varchar(32) NOT NULL, health varchar(32) NOT NULL, validated_at datetime(6) NULL, expires_at datetime(6) NULL, record_version bigint unsigned NOT NULL DEFAULT 1, PRIMARY KEY(id), UNIQUE KEY provider_id(provider_id), KEY provider_state(state,health)) {$charset};",
            'migrations' => "CREATE TABLE {$prefix}sabri_cf03_migrations (migration_id varchar(128) NOT NULL, checksum char(64) NOT NULL, status varchar(32) NOT NULL, started_at datetime(6) NOT NULL, completed_at datetime(6) NULL, error_code varchar(64) NULL, PRIMARY KEY(migration_id)) {$charset};",
        ];
    }
}
