<?php

declare(strict_types=1);

namespace Sabri\CF03\Persistence;

final class Schema
{
    public const VERSION = '1.0.0';

    /** @return array<string,string> */
    public static function tables(string $prefix): array
    {
        $charset = 'DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';
        return [
            'products' => "CREATE TABLE {$prefix}sabri_cf03_products (id bigint unsigned NOT NULL AUTO_INCREMENT, product_id varchar(128) NOT NULL, kind varchar(32) NOT NULL, billing_type varchar(32) NOT NULL, owner varchar(128) NOT NULL, entitlement_mapping varchar(191) NULL, status varchar(32) NOT NULL, policy_version varchar(64) NOT NULL, record_version bigint unsigned NOT NULL DEFAULT 1, created_at datetime(6) NOT NULL, updated_at datetime(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY product_id(product_id)) {$charset};",
            'prices' => "CREATE TABLE {$prefix}sabri_cf03_price_versions (id bigint unsigned NOT NULL AUTO_INCREMENT, price_version_id varchar(128) NOT NULL, product_id varchar(128) NOT NULL, amount_minor bigint unsigned NOT NULL, currency char(3) NOT NULL, region varchar(32) NOT NULL, tax_mode varchar(32) NOT NULL, effective_from datetime(6) NOT NULL, effective_until datetime(6) NULL, approval_ref varchar(191) NOT NULL, snapshot_hash char(64) NOT NULL, record_version bigint unsigned NOT NULL DEFAULT 1, PRIMARY KEY(id), UNIQUE KEY price_version_id(price_version_id), KEY product_region_currency(product_id,region,currency,effective_from)) {$charset};",
            'intents' => "CREATE TABLE {$prefix}sabri_cf03_payment_intents (id bigint unsigned NOT NULL AUTO_INCREMENT, intent_id varchar(128) NOT NULL, actor_ref varchar(191) NOT NULL, product_id varchar(128) NOT NULL, price_version_id varchar(128) NOT NULL, amount_minor bigint unsigned NOT NULL, currency char(3) NOT NULL, provider varchar(64) NOT NULL, provider_ref varchar(191) NULL, state varchar(32) NOT NULL, idempotency_key varchar(191) NOT NULL, request_hash char(64) NOT NULL, record_version bigint unsigned NOT NULL DEFAULT 1, created_at datetime(6) NOT NULL, updated_at datetime(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY intent_id(intent_id), UNIQUE KEY idempotency_scope(idempotency_key,actor_ref)) {$charset};",
            'provider_events' => "CREATE TABLE {$prefix}sabri_cf03_provider_events (id bigint unsigned NOT NULL AUTO_INCREMENT, provider varchar(64) NOT NULL, provider_event_id varchar(191) NOT NULL, raw_body_hash char(64) NOT NULL, signature_key_version varchar(64) NOT NULL, received_at datetime(6) NOT NULL, mapped_state varchar(32) NOT NULL, status varchar(32) NOT NULL, intent_id varchar(128) NULL, PRIMARY KEY(id), UNIQUE KEY provider_event(provider,provider_event_id)) {$charset};",
            'ledger_transactions' => "CREATE TABLE {$prefix}sabri_cf03_ledger_transactions (id bigint unsigned NOT NULL AUTO_INCREMENT, transaction_id varchar(128) NOT NULL, source_type varchar(64) NOT NULL, source_ref varchar(191) NOT NULL, effective_at datetime(6) NOT NULL, recorded_at datetime(6) NOT NULL, actor_ref varchar(191) NOT NULL, reason varchar(255) NOT NULL, period_id varchar(32) NOT NULL, reversal_of varchar(128) NULL, PRIMARY KEY(id), UNIQUE KEY transaction_id(transaction_id), UNIQUE KEY source_once(source_type,source_ref)) {$charset};",
            'ledger_entries' => "CREATE TABLE {$prefix}sabri_cf03_ledger_entries (id bigint unsigned NOT NULL AUTO_INCREMENT, transaction_id varchar(128) NOT NULL, account varchar(128) NOT NULL, direction varchar(8) NOT NULL, amount_minor bigint unsigned NOT NULL, currency char(3) NOT NULL, source_ref varchar(191) NOT NULL, PRIMARY KEY(id), KEY transaction_id(transaction_id), KEY account_currency(account,currency)) {$charset};",
            'subscriptions' => "CREATE TABLE {$prefix}sabri_cf03_subscriptions (id bigint unsigned NOT NULL AUTO_INCREMENT, subscription_id varchar(128) NOT NULL, actor_ref varchar(191) NOT NULL, product_id varchar(128) NOT NULL, price_version_id varchar(128) NOT NULL, provider_ref varchar(191) NULL, state varchar(32) NOT NULL, current_period_end datetime(6) NULL, grace_until datetime(6) NULL, record_version bigint unsigned NOT NULL DEFAULT 1, PRIMARY KEY(id), UNIQUE KEY subscription_id(subscription_id)) {$charset};",
            'invoices' => "CREATE TABLE {$prefix}sabri_cf03_invoices (id bigint unsigned NOT NULL AUTO_INCREMENT, invoice_id varchar(128) NOT NULL, invoice_number varchar(128) NOT NULL, actor_ref varchar(191) NOT NULL, status varchar(32) NOT NULL, amount_minor bigint unsigned NOT NULL, currency char(3) NOT NULL, snapshot_hash char(64) NOT NULL, snapshot_json longtext NOT NULL, created_at datetime(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY invoice_id(invoice_id), UNIQUE KEY invoice_number(invoice_number)) {$charset};",
            'refunds' => "CREATE TABLE {$prefix}sabri_cf03_refunds (id bigint unsigned NOT NULL AUTO_INCREMENT, refund_id varchar(128) NOT NULL, intent_id varchar(128) NOT NULL, amount_minor bigint unsigned NOT NULL, currency char(3) NOT NULL, requester_ref varchar(191) NOT NULL, reviewer_ref varchar(191) NULL, executor_ref varchar(191) NULL, reason varchar(255) NOT NULL, state varchar(32) NOT NULL, provider_ref varchar(191) NULL, record_version bigint unsigned NOT NULL DEFAULT 1, PRIMARY KEY(id), UNIQUE KEY refund_id(refund_id)) {$charset};",
            'outbox' => "CREATE TABLE {$prefix}sabri_cf03_outbox (id bigint unsigned NOT NULL AUTO_INCREMENT, event_id varchar(128) NOT NULL, event_type varchar(96) NOT NULL, aggregate_id varchar(128) NOT NULL, payload_json longtext NOT NULL, payload_hash char(64) NOT NULL, status varchar(32) NOT NULL, attempts int unsigned NOT NULL DEFAULT 0, available_at datetime(6) NOT NULL, created_at datetime(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY event_id(event_id), KEY delivery(status,available_at)) {$charset};",
            'audit' => "CREATE TABLE {$prefix}sabri_cf03_audit_events (id bigint unsigned NOT NULL AUTO_INCREMENT, audit_id varchar(128) NOT NULL, actor_ref varchar(191) NOT NULL, purpose varchar(128) NOT NULL, action varchar(128) NOT NULL, outcome varchar(32) NOT NULL, trace_id varchar(128) NOT NULL, metadata_json longtext NOT NULL, metadata_hash char(64) NOT NULL, created_at datetime(6) NOT NULL, PRIMARY KEY(id), UNIQUE KEY audit_id(audit_id), KEY trace_id(trace_id)) {$charset};",
            'migrations' => "CREATE TABLE {$prefix}sabri_cf03_migrations (migration_id varchar(128) NOT NULL, checksum char(64) NOT NULL, status varchar(32) NOT NULL, started_at datetime(6) NOT NULL, completed_at datetime(6) NULL, PRIMARY KEY(migration_id)) {$charset};",
        ];
    }
}
