<?php

declare(strict_types=1);

namespace Sabri\CF03\Application;

use DateTimeImmutable;
use InvalidArgumentException;
use Sabri\CF03\Contracts\QueryableFinancialRepository;
use Sabri\CF03\Domain\ChargebackCase;
use Sabri\CF03\Domain\DonationExpenseCategory;
use Sabri\CF03\Domain\FraudReviewCase;
use Sabri\CF03\Domain\Money;
use Sabri\CF03\Support\InvariantViolation;

final class RiskOperationsService
{
    public function __construct(private readonly QueryableFinancialRepository $repository,private readonly RuntimeConfiguration $configuration){}

    /** @return array<string,mixed> */
    public function openFraudReview(FraudReviewCase $case,DateTimeImmutable $createdAt):array{$record=['review_id'=>$case->reviewId(),'subject_ref'=>$case->subjectReference(),'risk_score'=>$case->riskScore(),'signals_json'=>$case->signals(),'hold_until'=>$case->holdUntil(),'state'=>$case->state(),'reviewer_ref'=>$case->reviewerReference(),'decision_reason'=>$case->decisionReason(),'record_version'=>$case->recordVersion(),'created_at'=>$createdAt,'updated_at'=>$createdAt];$this->repository->insert('fraud_reviews',$case->reviewId(),$record);return $record;}
    /** @return array<string,mixed> */
    public function decideFraudReview(string $reviewId,bool $approved,string $reviewer,string $reason,DateTimeImmutable $at,int $expectedVersion):array{$record=$this->require('fraud_reviews',$reviewId,$expectedVersion);$case=$this->fraud($record);$case->decide($approved,$reviewer,$reason,$at,$expectedVersion);return $this->updateFraud($reviewId,$record,$case,$at);}
    /** @return array<string,mixed> */
    public function appealFraudReview(string $reviewId,string $subjectReference,string $reason,DateTimeImmutable $at,int $expectedVersion):array{$record=$this->require('fraud_reviews',$reviewId,$expectedVersion);if((string)$record['subject_ref']!==$subjectReference){throw new InvariantViolation('Fraud appeal is outside subject scope.');}$case=$this->fraud($record);$case->appeal($reason,$expectedVersion);return $this->updateFraud($reviewId,$record,$case,$at);}
    /** @return array<string,mixed> */
    public function closeFraudReview(string $reviewId,DateTimeImmutable $at,int $expectedVersion):array{$record=$this->require('fraud_reviews',$reviewId,$expectedVersion);$case=$this->fraud($record);$case->close($expectedVersion);return $this->updateFraud($reviewId,$record,$case,$at);}

    /** @return array<string,mixed> */
    public function openChargeback(ChargebackCase $case,DateTimeImmutable $createdAt):array{$intent=$this->repository->get('intents',$case->paymentIntentId());if($intent===null||!in_array((string)$intent['state'],['captured','settled','disputed'],true)){throw new InvariantViolation('Chargeback requires a captured, settled or disputed canonical payment intent.');}if((string)$intent['currency']!==$case->disputedAmount()->currency()||(int)$intent['amount_minor']<$case->disputedAmount()->minorUnits()){throw new InvariantViolation('Chargeback amount exceeds the canonical payment or changes currency.');}$record=['case_id'=>$case->caseId(),'provider'=>$case->providerCode(),'provider_case_ref'=>$case->providerCaseReference(),'intent_id'=>$case->paymentIntentId(),'amount_minor'=>$case->disputedAmount()->minorUnits(),'currency'=>$case->disputedAmount()->currency(),'reason_code'=>$case->reasonCode(),'response_deadline'=>$case->responseDeadline(),'evidence_hash'=>$case->evidenceSha256(),'provider_fee_minor'=>$case->providerFee()?->minorUnits(),'state'=>$case->state(),'record_version'=>$case->recordVersion(),'created_at'=>$createdAt,'updated_at'=>$createdAt];$this->repository->insert('chargebacks',$case->caseId(),$record);return $record;}
    /** @return array<string,mixed> */
    public function requireChargebackEvidence(string $caseId,DateTimeImmutable $at,int $expectedVersion):array{$record=$this->require('chargebacks',$caseId,$expectedVersion);$case=$this->chargeback($record);$case->requireEvidence($at,$expectedVersion);return $this->updateChargeback($caseId,$record,$case,$at);}
    /** @return array<string,mixed> */
    public function submitChargebackEvidence(string $caseId,string $sha256,DateTimeImmutable $at,int $expectedVersion):array{$record=$this->require('chargebacks',$caseId,$expectedVersion);$case=$this->chargeback($record);$case->submitEvidence($sha256,$at,$expectedVersion);return $this->updateChargeback($caseId,$record,$case,$at);}
    /** @return array<string,mixed> */
    public function acceptChargebackEvidence(string $caseId,DateTimeImmutable $at,int $expectedVersion):array{$record=$this->require('chargebacks',$caseId,$expectedVersion);$case=$this->chargeback($record);$case->recordProviderAcceptance($expectedVersion);return $this->updateChargeback($caseId,$record,$case,$at);}
    /** @return array<string,mixed> */
    public function recordChargebackOutcome(string $caseId,bool $won,Money $providerFee,DateTimeImmutable $at,int $expectedVersion):array{$record=$this->require('chargebacks',$caseId,$expectedVersion);$case=$this->chargeback($record);$case->recordOutcome($won,$providerFee,$expectedVersion);return $this->updateChargeback($caseId,$record,$case,$at);}
    /** @return array<string,mixed> */
    public function adjustChargebackLedger(string $caseId,string $operatorReference,DateTimeImmutable $at,int $expectedVersion):array{$this->configuration->assertFinancialMutationReady();self::reference($operatorReference);$record=$this->require('chargebacks',$caseId,$expectedVersion);$case=$this->chargeback($record);if(!in_array($case->state(),['won','lost'],true)){throw new InvariantViolation('Chargeback outcome is not final.');}$transactionId='txn.chargeback.'.substr(hash('sha256',$caseId),0,32);$this->repository->transaction(function()use($case,$record,$transactionId,$operatorReference,$at,$expectedVersion,$caseId):void{if($this->repository->get('ledger_transactions',$transactionId)===null){$this->repository->insert('ledger_transactions',$transactionId,['transaction_id'=>$transactionId,'source_type'=>'chargeback_outcome','source_ref'=>$case->providerCode().':'.$case->providerCaseReference(),'effective_at'=>$at,'recorded_at'=>$at,'actor_ref'=>$operatorReference,'reason'=>$case->state()==='won'?'chargeback_won':'chargeback_lost','period_id'=>$at->format('Y-m'),'reversal_of'=>null,'trace_id'=>'trace:chargeback:'.substr(hash('sha256',$caseId),0,24)]);if($case->state()==='lost'){$this->entry($transactionId,$caseId.':loss','contra_income.chargeback','debit',$case->disputedAmount());$this->entry($transactionId,$caseId.':clearing-loss','asset.provider_clearing','credit',$case->disputedAmount());}$fee=$case->providerFee()??Money::zero($case->disputedAmount()->currency());if($fee->minorUnits()>0){$this->entry($transactionId,$caseId.':fee','expense.payment_processing','debit',$fee);$this->entry($transactionId,$caseId.':clearing-fee','asset.provider_clearing','credit',$fee);$expenseId='expense.chargeback.'.substr(hash('sha256',$caseId),0,28);$this->repository->insert('expenses',$expenseId,['expense_id'=>$expenseId,'occurred_at'=>$at,'amount_minor'=>$fee->minorUnits(),'currency'=>$fee->currency(),'category'=>DonationExpenseCategory::ADMINISTRATION_PAYMENT_CHARGES,'purpose'=>'Chargeback provider fee','payee_ref'=>'provider:'.$case->providerCode(),'approval_ref'=>'chargeback:'.$caseId,'receipt_status'=>'verified','founder_related'=>false,'public_disclosure_category'=>'administration_payment_charges','source_transaction_id'=>$transactionId,'record_version'=>1,'created_at'=>$at,'updated_at'=>$at]);}}$case->markLedgerAdjusted($expectedVersion);$this->updateChargeback($caseId,$record,$case,$at);});return ['case_id'=>$caseId,'state'=>'ledger_adjusted','transaction_id'=>$transactionId,'record_version'=>$expectedVersion+1];}
    /** @return array<string,mixed> */
    public function closeChargeback(string $caseId,DateTimeImmutable $at,int $expectedVersion):array{$record=$this->require('chargebacks',$caseId,$expectedVersion);$case=$this->chargeback($record);$case->close($expectedVersion);return $this->updateChargeback($caseId,$record,$case,$at);}

    /** @return array<string,mixed> */ private function require(string $collection,string $id,int $version):array{$record=$this->repository->get($collection,$id);if($record===null||(int)($record['version']??0)!==$version){throw new InvariantViolation('Risk record is missing or stale.');}return $record;}
    private function fraud(array $r):FraudReviewCase{return new FraudReviewCase((string)$r['review_id'],(string)$r['subject_ref'],(array)$r['signals_json'],new DateTimeImmutable((string)$r['created_at']),new DateTimeImmutable((string)$r['hold_until']),(string)$r['state'],(int)$r['version'],is_string($r['reviewer_ref']??null)?$r['reviewer_ref']:null,is_string($r['decision_reason']??null)?$r['decision_reason']:null);}
    private function chargeback(array $r):ChargebackCase{return new ChargebackCase((string)$r['case_id'],(string)$r['provider'],(string)$r['provider_case_ref'],(string)$r['intent_id'],new Money((int)$r['amount_minor'],(string)$r['currency']),(string)$r['reason_code'],new DateTimeImmutable((string)$r['created_at']),new DateTimeImmutable((string)$r['response_deadline']),(string)$r['state'],(int)$r['version'],is_string($r['evidence_hash']??null)?$r['evidence_hash']:null,isset($r['provider_fee_minor'])&&$r['provider_fee_minor']!==null?new Money((int)$r['provider_fee_minor'],(string)$r['currency']):null);}
    private function updateFraud(string $id,array $record,FraudReviewCase $case,DateTimeImmutable $at):array{return $this->repository->compareAndSwap('fraud_reviews',$id,(int)$record['version'],static function(array $current)use($case,$at):array{$current['state']=$case->state();$current['reviewer_ref']=$case->reviewerReference();$current['decision_reason']=$case->decisionReason();$current['updated_at']=$at;return $current;});}
    private function updateChargeback(string $id,array $record,ChargebackCase $case,DateTimeImmutable $at):array{return $this->repository->compareAndSwap('chargebacks',$id,(int)$record['version'],static function(array $current)use($case,$at):array{$current['state']=$case->state();$current['evidence_hash']=$case->evidenceSha256();$current['provider_fee_minor']=$case->providerFee()?->minorUnits();$current['updated_at']=$at;return $current;});}
    private function entry(string $transactionId,string $sourceRef,string $account,string $direction,Money $amount):void{$this->repository->insert('ledger_entries',$sourceRef,['transaction_id'=>$transactionId,'account'=>$account,'direction'=>$direction,'amount_minor'=>$amount->minorUnits(),'currency'=>$amount->currency(),'source_ref'=>$sourceRef]);}
    private static function reference(string $value):void{if(preg_match('/^[A-Za-z0-9][A-Za-z0-9._:-]{2,191}$/',$value)!==1){throw new InvalidArgumentException('Risk operator reference is invalid.');}}
}
